// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("./Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

var eq = Caml_obj.equal;

Test.run([
      [
        "DictTests.res",
        5,
        20,
        26
      ],
      "make"
    ], {}, eq, {});

Test.run([
      [
        "DictTests.res",
        7,
        20,
        31
      ],
      "fromArray"
    ], Object.fromEntries([[
            "foo",
            "bar"
          ]]), eq, {foo: "bar"});

Test.run([
      [
        "DictTests.res",
        10,
        13,
        35
      ],
      "getUnsafe - existing"
    ], Object.fromEntries([[
              "foo",
              "bar"
            ]])["foo"], eq, "bar");

Test.run([
      [
        "DictTests.res",
        16,
        13,
        34
      ],
      "getUnsafe - missing"
    ], ({})["foo"], eq, undefined);

exports.eq = eq;
/*  Not a pure module */
