// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("./Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

var eq = Caml_obj.equal;

Test.run([
      [
        "StringTests.res",
        5,
        20,
        47
      ],
      "String.equal optimization"
    ], false, eq, false);

exports.eq = eq;
/*  Not a pure module */
