// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("---");

console.log("Intl.PluralRules");

new Intl.PluralRules();

new Intl.PluralRules([
      "en-US",
      "en-GB"
    ]);

var _formatter = new Intl.PluralRules(undefined, {
      type: "ordinal",
      minimumSignificantDigits: 3,
      maximumSignificantDigits: 5
    });

var formatter = new Intl.PluralRules(["en-US"], {
      type: "ordinal",
      minimumSignificantDigits: 3,
      maximumSignificantDigits: 5
    });

console.log(formatter.resolvedOptions());

console.log(formatter.select(2.0));

console.log(formatter.select(2));

exports._formatter = _formatter;
exports.formatter = formatter;
/*  Not a pure module */
